[tox]
envlist = py{37,38,39,310,311,312,313}

[testenv]
platform =
    windows: win32
    linux: linux
    darwin: darwin
deps =
    pytest
    -r requirements.txt
passenv = *
commands =
    pytest fastrlock/tests --capture=no --strict {posargs}
